import type { Metadata } from "next";
import { DM_Mono, Inter, Space_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { FileText, Home, Link } from "lucide-react";
import { BriefcaseIcon, HomeIcon, LinkIcon } from "@heroicons/react/24/outline"; 
import Navbar from "@/components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });
const dmMono = DM_Mono({subsets: ['latin'] , weight: ['500', '300']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={clsx('', dmMono.className)}>
          <Navbar/>  
          {children}
        </body>
    </html>
  );
}
